apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/vcs-url: https://github.com/rhdemo/2021-shiptracker.git
    app.quarkus.io/build-timestamp: 2021-02-15 - 17:06:59 +0000
    app.quarkus.io/commit-id: bf083d834f7b2fbbd98d7246e20c2d75478fe540
  labels:
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/name: ship-tracker
  name: ship-tracker
  namespace: ship-tracker-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
      app.kubernetes.io/name: ship-tracker
  template:
    metadata:
      annotations:
        app.quarkus.io/vcs-url: https://github.com/rhdemo/2021-shiptracker.git
        app.quarkus.io/build-timestamp: 2021-02-15 - 17:06:59 +0000
        app.quarkus.io/commit-id: bf083d834f7b2fbbd98d7246e20c2d75478fe540
      labels:
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
        app.kubernetes.io/name: ship-tracker
    spec:
      containers:
      - env:
        - name: SHIPCOMMANDER_URL
          value: http://ship-commander-shipcommander.apps.summit-dev-aws.m7o7.p1.openshiftapps.com
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: QUARKUS_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgresql-shipdb-credentials
              key: database-user
        - name: QUARKUS_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-shipdb-credentials
              key: database-password
        - name: QUARKUS_DATASOURCE_JDBC_URL
          valueFrom:
            secretKeyRef:
              name: postgresql-shipdb-credentials
              key: database-connection-url
        image: sebi2706/ship-tracker:v6
        imagePullPolicy: Always
        name: ship-tracker
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
